version: 2.1
orbs:
  gravitee: gravitee-io/gravitee@dev:1.0.19
  secrethub: secrethub/cli@1.1.0

parameters:
    gh_cred:
        type: string
        default: ""
        description: "gh cred"
    cc_cred:
        type: string
        default: ""
        description: "cc cred"
jobs:
  prepare:
    docker:
      - image: cimg/base:2021.05
    steps:
      - secrethub/install
      - gravitee/sequential_builds:
         gh_cred: secrethub read graviteeio/cicd/graviteebot/github_personal_access_token
         cc_cred: secrethub read graviteeio/cicd/admin/circleci/nicolas/token
      - run: "hello where"
workflows:
  test-sequential:
    jobs:
      - prepare:
          context: cicd-orchestrator