version: 2.1
orbs:
  gravitee: gravitee-io/gravitee@dev:1.0.19
  secrethub: secrethub/cli@1.1.0

parameters:
    greeting:
        type: string
        default: ""
        description: "Greeting"
jobs:
  prepare:
    docker:
      - image: cimg/base:2021.05
    steps:
      - secrethub/install
      - gravitee/sequential_builds:
         greeting: secrethub read graviteeio/cicd/graviteebot/github_personal_access_token
                
workflows:
  test-sequential:
    jobs:
      - prepare:
          context: cicd-orchestrator