version: 2.1
orbs:
  gravitee: gravitee-io/gravitee@dev:1.0.19
  secrethub: secrethub/cli@1.1.0

parameters:
  greeting:
    type: string
    default: "Hello"
    description: "Greeting"

jobs:
  prepare:
    docker:
      - image: cimg/base:2021.05
    steps:
      - secrethub/install
      - run: |
              cc_cred=$(secrethub read graviteeio/cicd/admin/circleci/nicolas/token)
              builds=$(curl -s -H "Circle-Token:$cc_cred" https://circleci.com/api/v1.1/recent-builds?limit=15&shallow=true)
              # builds=$(curl -s -H "Circle-Token: 4a54d9abb17731983986624716e546d3e2c5b599"  https://circleci.com/api/v1.1/recent-builds?limit=15&shallow=true)
              echo $builds
      # - run: |
      #           gh_cred=$(secrethub read graviteeio/cicd/graviteebot/github_personal_access_token)
      #           cc_cred=$(secrethub read graviteeio/cicd/graviteebot/circleci/api/token)
      #           pr_data=$(echo $CIRCLE_PULL_REQUESTS | rev | awk -F '/' '{print $1 FS $3}' | rev)
      #           url_part=$(echo $(echo $pr_data | awk -F '/' '{print $1}')/pulls/$(echo $pr_data | awk -F '/' '{print $2}'))
      #           issue_url=$(curl -s -u graviteeio:$gh_cred https://api.github.com/repos/gravitee-io/$url_part | jq '.body')
      #           # curl -s -u graviteeio:$gh_cred https://api.github.com/repos/gravitee-io/$url_part
      #           issue_number=$(echo $issue_url | rev | awk -F'"' '$0=$2' | awk -F '/' '{print $1}'| rev)
      #           pr_search=$(curl -s -u graviteeio:$gh_cred "https://api.github.com/repos/gravitee-io/issues/issues/$issue_number/timeline?per_page=100" -H "Accept: application/vnd.github.mockingbird-preview")

      #           repos=$(echo $pr_search | jq -r '.[] | select(.source.issue.pull_request != null) | select(.source.issue.state == "open") | select(.source.type == "issue") |.source.issue.repository.name')
      #           builds=$(curl -s -H "Circle-Token:$cc_cred"  https://circleci.com/api/v1.1/recent-builds?limit=15&shallow=true)
      #           curl -s -H "Circle-Token:$cc_cred" https://circleci.com/api/v1.1/recent-builds?limit=15&shallow=true
      #           # release=$(curl -s -u Novachevski:$gh_cred https://raw.githubusercontent.com/gravitee-io/release/master/release.json)
      #           # # echo $release
      #           # echo $builds
      #           # for repo in $repos; do 
      #           # clean_repo=$(echo $repo | xargs)
      #           # location=$(echo $release | jq '.buildDependencies[]' |grep -n $clean_repo | awk '{print $1}');
      #           # # echo $location$clean_repo
      #           # tempi=$(echo $builds |jq -r --arg repo "$clean_repo" '.[] |{reponame, build_url, status} | select(.reponame==$repo)')
      #           # # echo $tempi
      #           # if [ -z "$tempi" ]; then sleep 1; else project_list+=($location$repo); fi
      #           # done
      #           # # for neso in ${project_list[@]}; do echo $neso; done
workflows:
  test-sequential:
    jobs:
      - prepare:
          context: cicd-orchestrator