version: 2.1
orbs:
  gravitee: gravitee-io/gravitee@dev:1.0.19
  secrethub: secrethub/cli@1.1.0

parameters:
    gh_cred:
        type: string
        default: ""
        description: "gh cred"
    cc_cred:
        type: string
        default: ""
        description: "cc cred"
jobs:
  prepare:
    docker:
      - image: cimg/base:2021.05
    steps:
      - secrethub/install
      # - gravitee/sequential_builds:
        #  gh_cred: $(secrethub read graviteeio/cicd/graviteebot/github_personal_access_token)
        #  cc_cred: $(secrethub read graviteeio/cicd/admin/circleci/nicolas/token)
      - run: printenv
      - run: |
              pr_num=echo $CIRCLE_PULL_REQUEST | rev | awk  -F "/" '{print $1}' | rev
              echo "$CIRCLE_PROJECT_REPONAME"
              # echo $artifact_name
              # 7z a gravitee-demo-${version}.zip ./devops-demo-$version/*

              # curl -u $artifactory_creds -T $artifact_name "$artifactory_url"
workflows:
  test-sequential:
    jobs:
      - prepare:
          context: cicd-orchestrator