version: 2.1
orbs:
  gravitee: gravitee-io/gravitee@dev:1.0.19
  secrethub: secrethub/cli@1.1.0

parameters:
  greeting:
    type: string
    default: "Hello"
    description: "Greeting"

jobs:
  prepare:
    docker:
      - image: cimg/base:2021.05
    steps:
      - secrethub/install
      - run: |
                gh_cred=$(secrethub read graviteeio/cicd/graviteebot/github_personal_access_token)
                cc_cred=$(secrethub read graviteeio/cicd/admin/circleci/nicolas/token)
                pr_data=$(echo $CIRCLE_PULL_REQUESTS | rev | awk -F '/' '{print $1 FS $3}' | rev)
                url_part=$(echo $(echo $pr_data | awk -F '/' '{print $1}')/pulls/$(echo $pr_data | awk -F '/' '{print $2}'))
                echo $url_part
                issue_url=$(curl -s -u graviteeio:$gh_cred https://api.github.com/repos/gravitee-io/$url_part | jq '.body')
                # curl -s -u graviteeio:$gh_cred https://api.github.com/repos/gravitee-io/$url_part
                # echo $issue_url
                issue_number=$(echo $issue_url | rev | awk -F'"' '$0=$2' | awk -F '/' '{print $1}'| rev)
                echo $issue_number
                pr_search=$(curl -s -u graviteeio:$gh_cred "https://api.github.com/repos/Novachevski/issues/issues/5716/timeline?per_page=100" -H "Accept: application/vnd.github.mockingbird-preview")
                echo $pr_search

workflows:
  test-sequential:
    jobs:
      - prepare:
          context: cicd-orchestrator